apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: book-dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
  annotations:
    codefresh.io/product: book
spec:
  project: default
  destination:
    name: in-cluster
    namespace: dev
  source:
    path: helm-guestbook
    repoURL: https://github.com/chen-keinan/argocd-example-apps.git
    targetRevision: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=false
