apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: pre-action
  annotations:
    version: 0.0.1
    description: 'promotion workflow template'
spec:
  serviceAccountName: promotion-template1
  arguments:
    parameters:
    - name: APP_NAME
  entrypoint: echo-pre-action
  templates:
  - name: echo-pre-action2
    script:
      image: alpine
      command:
      - sh
      source: |
        echo "syncing {{ workflow.parameters.APP_NAME }} "
        # exit 1