apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: relative-path-dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
  annotations:
    codefresh.io/product: relative-path-test
spec:
  project: default
  source:
    path: resources
    repoURL: https://github.com/kim-codefresh/relative-path-dev.git
    targetRevision: dev
  destination:
    name: in-cluster
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=false
