apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rollout-staging
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
  annotations:
    codefresh.io/product: rollout
  labels:
    env: staging
spec:
  project: default
  source:
    repoURL: https://github.com/kim-codefresh/rollout-test-git-source.git
    targetRevision: main
    path: rollout-apps/staging
  destination:
    name: in-cluster
    namespace: staging
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
