apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-staging-2-local
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  source:
    path: .
    repoURL: https://github.com/kim-codefresh/codefresh-runtime-apps-local.git
    targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: staging-2
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      allowEmpty: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=false
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=false
