apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-prod-local
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
  annotations:
    codefresh.io/product: my-product
spec:
  project: default
  source:
    path: resources-prod
    repoURL: https://github.com/kim-codefresh/guestbook-local.git
    targetRevision: local
  destination:
    name: in-cluster
    namespace: production
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      allowEmpty: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=true
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=false
